### ISSUE TITLE
Should fix hard-coded paths

### ISSUE THREAD

**Issue by mcclearyj** [GeorgeVassilakis/wcs_beheader#1]
Make it an argument

**Comment by emaadparacha** [comment]
We got this fixed in PR https://github.com/GeorgeVassilakis/wcs_beheader/pull/2 and PR https://github.com/GeorgeVassilakis/wcs_beheader/pull/5

**Comment by GeorgeVassilakis** [comment]
Closed with PR #2 and PR #5
