### ISSUE TITLE
astrometry-out not saved in image directory?

### ISSUE THREAD

**Issue by mcclearyj** [GeorgeVassilakis/wcs_beheader#4]
I am running `wcs_beheader` on a Mac M2 with the astrometry-net code installed via brew (see [here](https://astrometry.net/doc/build.html#mac-os-x-using-homebrew)) in a dedicated conda environment.

When `--file [image]` is passed as an argument to `runner.py`, the `astrometry-out` folder is saved locally (in wcs_beheader) not in the image directory. I found the same behavior with `--dir [image_directory]`. This results in the failure of the rest of the code, since it is looking for a `*.new` file.

If I try to run wcs_beheader in the image directory, then the code fails because it can't find the actual scripts. I tried updating my path to include my wcs_beheader installation directory, but still no luck. 

Any thoughts?

**Comment by mcclearyj** [comment]
I think that this is the offending line: https://github.com/GeorgeVassilakis/wcs_beheader/blame/be56a092697813b20e5bcdf31a4237db53cf751c/update_wcs.py#L17 

Instead of `cwd`, something like `os.path.basedir([image_name])` would be better

**Comment by GeorgeVassilakis** [comment]
Eric fixed this, and I gave it to Emaad to push. Emaad says he will be pushing that today!

**Comment by emaadparacha** [comment]
PR https://github.com/GeorgeVassilakis/wcs_beheader/pull/5 has this fixed using Eric's updates

**Comment by GeorgeVassilakis** [comment]
Closed with PR #5
